#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _AMPANMDA_reg(void);
extern void _E3_NMDA_reg(void);
extern void _Exp2NMDA_Wang_reg(void);
extern void _IA_reg(void);
extern void _Ih_reg(void);
extern void _KahpM95_reg(void);
extern void _KahpM95_CA3_reg(void);
extern void _Kaxon_reg(void);
extern void _KdBG40_reg(void);
extern void _Kdend_reg(void);
extern void _Ksoma_reg(void);
extern void _Naaxon_reg(void);
extern void _Nadend_reg(void);
extern void _Nasoma_reg(void);
extern void _STDPE2_reg(void);
extern void _STDPE2_asym_reg(void);
extern void _borgka_reg(void);
extern void _borgkm_reg(void);
extern void _burststim2_reg(void);
extern void _cacumm_reg(void);
extern void _cacumm_CA3_reg(void);
extern void _cad_reg(void);
extern void _cadiv_reg(void);
extern void _cadyn_reg(void);
extern void _cagk_reg(void);
extern void _cagkCA3_reg(void);
extern void _cagk_CA3_reg(void);
extern void _cal_reg(void);
extern void _cal2_reg(void);
extern void _cal2_CA3_reg(void);
extern void _calH_reg(void);
extern void _can2_reg(void);
extern void _can2_CA3_reg(void);
extern void _cancr_reg(void);
extern void _car_reg(void);
extern void _cat_reg(void);
extern void _cat_CA3_reg(void);
extern void _ccanl_reg(void);
extern void _ch_CavL_reg(void);
extern void _ch_CavN_reg(void);
extern void _ch_HCN_reg(void);
extern void _ch_KCaS_reg(void);
extern void _ch_Kdrfast_reg(void);
extern void _ch_KvA_reg(void);
extern void _ch_KvCaB_reg(void);
extern void _ch_KvGroup_reg(void);
extern void _ch_KvM_reg(void);
extern void _ch_Navcck_reg(void);
extern void _ch_leak_reg(void);
extern void _d3_reg(void);
extern void _distr_reg(void);
extern void _distr_CA3_reg(void);
extern void _gabaa_reg(void);
extern void _gabab_reg(void);
extern void _glutamate_reg(void);
extern void _gskch_reg(void);
extern void _h_reg(void);
extern void _h_CA3_reg(void);
extern void _hha2_reg(void);
extern void _iccr_reg(void);
extern void _ichan2_reg(void);
extern void _ichan2aa_reg(void);
extern void _ichan2bc_reg(void);
extern void _ichan2bs_reg(void);
extern void _ichan2vip_reg(void);
extern void _ikscr_reg(void);
extern void _izhi_reg(void);
extern void _kadist_reg(void);
extern void _kadistcr_reg(void);
extern void _kahp_reg(void);
extern void _kaprox_reg(void);
extern void _kaprox_CA3_reg(void);
extern void _kca_reg(void);
extern void _kd_reg(void);
extern void _kd_CA3_reg(void);
extern void _kdr_reg(void);
extern void _kdrca1_reg(void);
extern void _kdrca1_CA3_reg(void);
extern void _kdrcr_reg(void);
extern void _km_reg(void);
extern void _km_CA3_reg(void);
extern void _lca_reg(void);
extern void _my_exp2syn_reg(void);
extern void _na3n_reg(void);
extern void _na3n_CA3_reg(void);
extern void _nafcr_reg(void);
extern void _nahh_reg(void);
extern void _namir_reg(void);
extern void _nap_reg(void);
extern void _naxn_reg(void);
extern void _naxn_CA3_reg(void);
extern void _nca_reg(void);
extern void _nmda_reg(void);
extern void _somacar_reg(void);
extern void _vecstim_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," AMPANMDA.mod");
    fprintf(stderr," E3_NMDA.mod");
    fprintf(stderr," Exp2NMDA_Wang.mod");
    fprintf(stderr," IA.mod");
    fprintf(stderr," Ih.mod");
    fprintf(stderr," KahpM95.mod");
    fprintf(stderr," KahpM95_CA3.mod");
    fprintf(stderr," Kaxon.mod");
    fprintf(stderr," KdBG40.mod");
    fprintf(stderr," Kdend.mod");
    fprintf(stderr," Ksoma.mod");
    fprintf(stderr," Naaxon.mod");
    fprintf(stderr," Nadend.mod");
    fprintf(stderr," Nasoma.mod");
    fprintf(stderr," STDPE2.mod");
    fprintf(stderr," STDPE2_asym.mod");
    fprintf(stderr," borgka.mod");
    fprintf(stderr," borgkm.mod");
    fprintf(stderr," burststim2.mod");
    fprintf(stderr," cacumm.mod");
    fprintf(stderr," cacumm_CA3.mod");
    fprintf(stderr," cad.mod");
    fprintf(stderr," cadiv.mod");
    fprintf(stderr," cadyn.mod");
    fprintf(stderr," cagk.mod");
    fprintf(stderr," cagkCA3.mod");
    fprintf(stderr," cagk_CA3.mod");
    fprintf(stderr," cal.mod");
    fprintf(stderr," cal2.mod");
    fprintf(stderr," cal2_CA3.mod");
    fprintf(stderr," calH.mod");
    fprintf(stderr," can2.mod");
    fprintf(stderr," can2_CA3.mod");
    fprintf(stderr," cancr.mod");
    fprintf(stderr," car.mod");
    fprintf(stderr," cat.mod");
    fprintf(stderr," cat_CA3.mod");
    fprintf(stderr," ccanl.mod");
    fprintf(stderr," ch_CavL.mod");
    fprintf(stderr," ch_CavN.mod");
    fprintf(stderr," ch_HCN.mod");
    fprintf(stderr," ch_KCaS.mod");
    fprintf(stderr," ch_Kdrfast.mod");
    fprintf(stderr," ch_KvA.mod");
    fprintf(stderr," ch_KvCaB.mod");
    fprintf(stderr," ch_KvGroup.mod");
    fprintf(stderr," ch_KvM.mod");
    fprintf(stderr," ch_Navcck.mod");
    fprintf(stderr," ch_leak.mod");
    fprintf(stderr," d3.mod");
    fprintf(stderr," distr.mod");
    fprintf(stderr," distr_CA3.mod");
    fprintf(stderr," gabaa.mod");
    fprintf(stderr," gabab.mod");
    fprintf(stderr," glutamate.mod");
    fprintf(stderr," gskch.mod");
    fprintf(stderr," h.mod");
    fprintf(stderr," h_CA3.mod");
    fprintf(stderr," hha2.mod");
    fprintf(stderr," iccr.mod");
    fprintf(stderr," ichan2.mod");
    fprintf(stderr," ichan2aa.mod");
    fprintf(stderr," ichan2bc.mod");
    fprintf(stderr," ichan2bs.mod");
    fprintf(stderr," ichan2vip.mod");
    fprintf(stderr," ikscr.mod");
    fprintf(stderr," izhi.mod");
    fprintf(stderr," kadist.mod");
    fprintf(stderr," kadistcr.mod");
    fprintf(stderr," kahp.mod");
    fprintf(stderr," kaprox.mod");
    fprintf(stderr," kaprox_CA3.mod");
    fprintf(stderr," kca.mod");
    fprintf(stderr," kd.mod");
    fprintf(stderr," kd_CA3.mod");
    fprintf(stderr," kdr.mod");
    fprintf(stderr," kdrca1.mod");
    fprintf(stderr," kdrca1_CA3.mod");
    fprintf(stderr," kdrcr.mod");
    fprintf(stderr," km.mod");
    fprintf(stderr," km_CA3.mod");
    fprintf(stderr," lca.mod");
    fprintf(stderr," my_exp2syn.mod");
    fprintf(stderr," na3n.mod");
    fprintf(stderr," na3n_CA3.mod");
    fprintf(stderr," nafcr.mod");
    fprintf(stderr," nahh.mod");
    fprintf(stderr," namir.mod");
    fprintf(stderr," nap.mod");
    fprintf(stderr," naxn.mod");
    fprintf(stderr," naxn_CA3.mod");
    fprintf(stderr," nca.mod");
    fprintf(stderr," nmda.mod");
    fprintf(stderr," somacar.mod");
    fprintf(stderr," vecstim.mod");
    fprintf(stderr, "\n");
  }
  _AMPANMDA_reg();
  _E3_NMDA_reg();
  _Exp2NMDA_Wang_reg();
  _IA_reg();
  _Ih_reg();
  _KahpM95_reg();
  _KahpM95_CA3_reg();
  _Kaxon_reg();
  _KdBG40_reg();
  _Kdend_reg();
  _Ksoma_reg();
  _Naaxon_reg();
  _Nadend_reg();
  _Nasoma_reg();
  _STDPE2_reg();
  _STDPE2_asym_reg();
  _borgka_reg();
  _borgkm_reg();
  _burststim2_reg();
  _cacumm_reg();
  _cacumm_CA3_reg();
  _cad_reg();
  _cadiv_reg();
  _cadyn_reg();
  _cagk_reg();
  _cagkCA3_reg();
  _cagk_CA3_reg();
  _cal_reg();
  _cal2_reg();
  _cal2_CA3_reg();
  _calH_reg();
  _can2_reg();
  _can2_CA3_reg();
  _cancr_reg();
  _car_reg();
  _cat_reg();
  _cat_CA3_reg();
  _ccanl_reg();
  _ch_CavL_reg();
  _ch_CavN_reg();
  _ch_HCN_reg();
  _ch_KCaS_reg();
  _ch_Kdrfast_reg();
  _ch_KvA_reg();
  _ch_KvCaB_reg();
  _ch_KvGroup_reg();
  _ch_KvM_reg();
  _ch_Navcck_reg();
  _ch_leak_reg();
  _d3_reg();
  _distr_reg();
  _distr_CA3_reg();
  _gabaa_reg();
  _gabab_reg();
  _glutamate_reg();
  _gskch_reg();
  _h_reg();
  _h_CA3_reg();
  _hha2_reg();
  _iccr_reg();
  _ichan2_reg();
  _ichan2aa_reg();
  _ichan2bc_reg();
  _ichan2bs_reg();
  _ichan2vip_reg();
  _ikscr_reg();
  _izhi_reg();
  _kadist_reg();
  _kadistcr_reg();
  _kahp_reg();
  _kaprox_reg();
  _kaprox_CA3_reg();
  _kca_reg();
  _kd_reg();
  _kd_CA3_reg();
  _kdr_reg();
  _kdrca1_reg();
  _kdrca1_CA3_reg();
  _kdrcr_reg();
  _km_reg();
  _km_CA3_reg();
  _lca_reg();
  _my_exp2syn_reg();
  _na3n_reg();
  _na3n_CA3_reg();
  _nafcr_reg();
  _nahh_reg();
  _namir_reg();
  _nap_reg();
  _naxn_reg();
  _naxn_CA3_reg();
  _nca_reg();
  _nmda_reg();
  _somacar_reg();
  _vecstim_reg();
}
